version: '3'

services:
  web:
    build: ./LIDcode_backend
    command: gunicorn --bind 0.0.0.0:8000 LIDcode_backend.wsgi
    volumes:
      - ./LIDcode_backend/:/usr/src/LIDcode_backend/
    ports:
      - 8000:8000
    env_file:
      - ./LIDcode_backend/.env.dev
    restart: always