# Generated by Django 4.0.5 on 2022-06-12 19:38

import django.contrib.postgres.fields.citext
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.citext.CITextField()),
                ('status', django.contrib.postgres.fields.citext.CITextField()),
                ('description', django.contrib.postgres.fields.citext.CITextField(blank=True, null=True)),
                ('numberofparticipants', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
                ('regulations', django.contrib.postgres.fields.citext.CITextField()),
                ('timetable', django.contrib.postgres.fields.citext.CITextField()),
                ('results', django.contrib.postgres.fields.citext.CITextField(blank=True, null=True)),
                ('materials', django.contrib.postgres.fields.citext.CITextField(blank=True, null=True)),
            ],
            options={
                'db_table': ' event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('name', django.contrib.postgres.fields.citext.CITextField()),
                ('link', django.contrib.postgres.fields.citext.CITextField()),
            ],
            options={
                'db_table': 'organizers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('name', django.contrib.postgres.fields.citext.CITextField()),
                ('link', django.contrib.postgres.fields.citext.CITextField()),
            ],
            options={
                'db_table': 'sponsors',
                'managed': False,
            },
        ),
    ]
