# Generated by Django 4.0.5 on 2022-06-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainList', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False, 'ordering': ['timetable', 'name'], 'verbose_name': 'Соревнование', 'verbose_name_plural': 'Соревнования'},
        ),
        migrations.AlterModelOptions(
            name='organizers',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Организатор', 'verbose_name_plural': 'Организаторы'},
        ),
        migrations.AlterModelOptions(
            name='sponsors',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Спонсор', 'verbose_name_plural': 'Спонсоры'},
        ),
    ]
