# Generated by Django 4.0.5 on 2022-06-22 19:07

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainList', '0002_alter_event_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.citext.CITextField(verbose_name='Наименование команды')),
                ('emailadress', django.contrib.postgres.fields.citext.CITextField(verbose_name='Электронная почта')),
                ('phonenumber', django.contrib.postgres.fields.citext.CITextField(verbose_name='Номер телефона')),
                ('organization', django.contrib.postgres.fields.citext.CITextField(verbose_name='Организация')),
                ('university', django.contrib.postgres.fields.citext.CITextField(blank=True, null=True, verbose_name='Университет')),
                ('university_faculty', django.contrib.postgres.fields.citext.CITextField(blank=True, null=True, verbose_name='Факультет')),
                ('university_course', django.contrib.postgres.fields.citext.CITextField(blank=True, null=True, verbose_name='Курс')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.citext.CITextField(verbose_name='Наименование команды')),
            ],
        ),
    ]
