# Generated by Django 4.0.5 on 2022-06-27 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainList', '0003_alter_team_coach_alter_team_contactperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='contactPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='my_contactPerson', to='mainList.participant'),
        ),
    ]
