# Generated by Django 4.0.5 on 2022-06-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainList', '0004_alter_team_contactperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_coach', to='mainList.participant'),
        ),
        migrations.AlterField(
            model_name='team',
            name='contactPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_contactPerson', to='mainList.participant'),
        ),
    ]
