# Generated by Django 4.0.5 on 2022-06-22 19:12

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainList', '0004_alter_participant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=django.contrib.postgres.fields.citext.CITextField(verbose_name='Наименование команды'),
        ),
    ]
