# Generated by Django 4.0.5 on 2022-06-27 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainList', '0005_alter_team_coach_alter_team_contactperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timeNow',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_coach', to='mainList.participant', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='team',
            name='contactPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_contactPerson', to='mainList.participant', verbose_name='Контактное лицо'),
        ),
    ]
