# Generated by Django 4.0.5 on 2022-06-22 19:33

import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainList', '0005_alter_participant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='my_coach', to='mainList.participant'),
        ),
        migrations.AddField(
            model_name='team',
            name='contactPerson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='my_contactPerson', to='mainList.participant'),
        ),
        migrations.AddField(
            model_name='team',
            name='teamMembers',
            field=models.ManyToManyField(to='mainList.participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=django.contrib.postgres.fields.citext.CITextField(verbose_name='ФИО'),
        ),
    ]
