# Generated by Django 4.0.5 on 2022-06-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainList', '0006_team_coach_team_contactperson_team_teammembers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
    ]
