# Generated by Django 4.0.5 on 2022-06-24 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainList', '0007_alter_participant_options_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='participant',
            table='participant',
        ),
        migrations.AlterModelTable(
            name='team',
            table='team',
        ),
    ]
